### ISSUE TITLE
Optimize the NewHelmValuesGenerator implementation

### ISSUE THREAD

**Issue by markgoddard** [cofide/cofidectl#10]
In addition to adding test coverage for the NewHelmValuesGenerator implementation (and it's associated methods), there may be several ways to improve its implementation, including:

1. add a function to build quoted, dotted keys:

```go
func keyName(sections ...string) string {}
```

2. Build up sections incrementally:

```go
func (g *HelmValuesGenerator) section(names ...string) helmValuesSection {}

type helmValuesSection struct {
    names []string
    generator *HelmValuesGenerator
}


func (s Section) section(names ...string) helmValuesSection {}

func (s Section) set(name string, val any) {}

// Then build up sections:

agent = g.section("spire-agent")
agent.set("logLevel", "DEBUG")
agent.section("server").set("address", "spire-server.spire")
```

**Comment by markgoddard** [comment]
While working on #5 , I bumped up against the use of CUE to build the Helm values.

Comment from the code:

We need to merge the values generated by this function with the user-specified extra helm values.
CUE does not easily handle merging values with multiple levels of precedence, since it sees different concrete values for the same path as a conflict. It supports disjunctions with defaults, but that would only work for a 2-level merge.

For now we can start with the higher precedence user values, then merge in the defaults to paths that do not exist.
TODO: Revisit the use of CUE here, consider reworking to use native Go types with a merge function.

https://github.com/cofide/cofidectl/pull/51/files#diff-0d44b61e7d05cefa049422df7917d212564419fbf2a5a9964b79f51daaf5138fR144

**Comment by nialdaly** [comment]
With the work completed in #51 and #62, this issue has been completed.
